---
Robots:
- initial_state: [0, -750, 1.57080]   # pi/2 = 1.57080
  sensorConfig: config/sensors/bearing.yaml
  dynamicsConfig: config/dynamics/dubins_car.yaml


targetConfig: config/targetModel.yaml
plannerConfig: config/planner.yaml

Tmax: 10
samp: 1.0
map_min: [-1000, -1000]
map_max: [1000, 1000]

# Estimator/planner info
clutter_density: 0.03183  # 3.183 = 20 per 360 degrees ~ 1 every 18 degrees
gate_level: 0.99
estimator_verbose: False
horizon: 10  # planning horizon
n_controls: 5  # Re-planning time
