---
targ_dim: 4
IDs: [100, 200, 300, 400, 500]
y0: # initial states of targets
  - [-500, -500, 15, 20]
  - [500, -500, -15, 20]
#  - [-750, -300, -20, 10]
#  - [-750, -200, -20, -10]
  #- [-750, -150, 0, 0]

cov_pos: 10000  # prior covariance in each
cov_vel: 25
process_cov_pos: 10  # covariance in the target motion model
process_cov_vel: 0.5