---
Robots:
- initial_state: [0, -750, 1.57080]   # pi/2 = 1.57080, pi/4 = 0.7854
#  sensorConfig: config/sensors/bearing.yaml
  dynamicsConfig: config/dynamics/dubins_car.yaml

sensorConfig: config/sensors/bearing.yaml
targetConfig: config/targetModel.yaml
plannerConfig: config/planner.yaml

Tmax: 90
samp: 1.0
random_seed: 1
map_min: [-1200, -1200]
map_max: [1200, 1200]

# Estimator/planner info
clutter_density: 0.03183  # 3.183 = 20 per 360 degrees ~ 1 every 18 degrees
gate_level: 0.99
estimator_verbose: False
horizon: 5  # planning horizon
n_controls: 5  # Re-planning time
sequential_resolution_update_flag: 1  # 0 if resolution update should be done in one step
