---
# Planner configuration for forward value iteration
#cost: log_det
#cost: log_det_plus_SD
cost: max_eig
#cost: gate_cost
#cost: delta_bearing
final_cost: False

# action parameters
speed: 0.29
turn_radius: 0.92
dt: 2 # seconds

# filter type in
#filter_type: kalman
#filter_type: JPDAF
filter_type: JPDAF_merged

FOV_flag: True
log_file: log/plan.json
log_flag: True
verbose: False


