---
targ_dim: 4
IDs: [100, 200, 300, 400, 500, 600, 700, 800]
y0: # initial states of targets
  - [4.25, -0.3, -0.1, 0]
  - [5.4, -2.54, -0.1, 0]
  - [-2.5, -5, 0.1, 0]
  - [-5, -7.5, 0.1, 0]
#  - [-750, 80, -20, 10]
#  - [-750, -10, 0, 0]
#  - [-750, 40, -20, -10]

cov_pos: 0.1  # prior covariance in position
cov_vel: 0.001  # prior covariance in velocity
process_cov_pos: 5  # covariance in the position in the target motion model
process_cov_vel: 0.1 # covariance in velocity in target motion model
process_noise: 0.00001 # constant used as multiplier in process noise covariance  (variance of acceleration disturbanc)