---
targ_dim: 4
IDs: [100, 200, 300, 400, 500, 600]
y0: # initial states of targets
  - [3.5, 6.5, -1, 0]
  - [-500, 500, 10, 0]
#  - [-1000, 1000, 20, 0]w
#  - [-750, 80, -20, 10]
#  - [-750, -10, 0, 0]
#  - [-750, 40, -20, -10]

cov_pos: 1  # prior covariance in each
cov_vel: 0
process_cov_pos: 5  # covariance in the target motion model
process_cov_vel: 0.1
process_noise: 0.01 # constant used as multiplier in process noise covariance